### PR TITLE
Improve notifications and improve test_action

### PR DESCRIPTION
**Pull request by fepitre**
https://github.com/QubesOS/qubes-issues/issues/7835
https://github.com/QubesOS/qubes-issues/issues/8067

### CODE REVIEW

**Comment by fepitre** [comment]
For now it fails at ISO build because Fedora 38 template is used for `builder-dvm`. Indeed, an update for template community key is needed https://github.com/QubesOS/qubes-qubes-release/pull/21 into `qubes-builderv2` submodule for installer.

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
test_rpc results in a timeout, few other fails for reasons related to this PR - probably needs updating, at least some notification text (if they really match what is expected).

**Comment by fepitre** [comment]
Something is wrong this is not the right branch and these problems are already solved since a while.

**Comment by fepitre** [comment]
My bad, i was confused with previous notifications. I'm fixing the one for ISO which is now working :)

**Review by marmarek — APPROVED** [review]

**Pull request merged**
